### ISSUE TITLE
Python demo issue

### ISSUE THREAD

**Issue by youkchan** [LNP-BP/rgb-sdk#56]
Hi! I tried to use python' demo to understand RGB protocol. But It didn't work for me.

**Issue**
- Used [these instructions ](https://github.com/rgb-org/rgb-sdk/tree/master/bindings/python)to build python' artifacts on MacOS using docker.
 ->Python' Dockerfile seems to be a little bit old and I fixed it for now.
     line 25 `COPY rust-lib /rgb-sdk/rust-lib`-> `COPY librgb /rgb-sdk/librgb`

- Execute Python demo
`$python3 example.py` (Python version is 3.9.5)

**Error**
```
$ python3 example.py 
Traceback (most recent call last):
  File "/Users/my-directory/rgb/rgb-sdk/demo/python/example.py", line 9, in <module>
    from rgb_node import RGBNode
  File "/Users/my-directory/rgb/rgb-sdk/demo/python/../../wrappers/python/rgb_node.py", line 7, in <module>
    from rgb import *
  File "/Users/my-directory/rgb/rgb-sdk/demo/python/../../bindings/python/rgb.py", line 15, in <module>
    import _rgb
ModuleNotFoundError: No module named '_rgb'
```

At glance, it looks like a very basic problem, I know...

**My  directory(/rgb-sdk/binding/python/) contents**
```
.gitignore
Dockerfile
README.md
__pycache__
_rgb.cpython-37m-x86_64-linux-gnu.so
rgb.py
setup.py
swig.i
```

**Warning**
When Compiling using docker, some warning occurs.
```
Step 8/14 : RUN . $HOME/.nvm/nvm.sh && npm install --unsafe-perm
 ---> Running in 301d88add3e2

> rgblib@0.2.0-beta.1 preinstall /rgb-sdk/bindings/npm
> cargo build --release --manifest-path ../../librgb/Cargo.toml && swig -javascript -node -c++ swig.i
　... 
   Compiling lnpbp_services v0.2.0
   Compiling rgb_node v0.2.2
    Finished release [optimized] target(s) in 23m 23s
../../librgb/librgb.h:20: Warning 451: Setting a const char * variable may leak memory.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

> rgblib@0.2.0-beta.1 install /rgb-sdk/bindings/npm
> node ./node_modules/node-gyp/bin/node-gyp.js rebuild

make: Entering directory '/rgb-sdk/bindings/npm/build'
  CXX(target) Release/obj.target/rgblib/swig_wrap.o
../swig_wrap.cxx: In function 'void SWIGV8_AddStaticVariable(v8::Handle<v8::Object>, const char*, SwigV8AccessorGetterCallback, SwigV8AccessorSetterCallback)':
../swig_wrap.cxx:1524:87: warning: ignoring return value of 'v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType)', declared with attribute warn_unused_result [-Wunused-result]
   obj->SetAccessor(SWIGV8_CURRENT_CONTEXT(), SWIGV8_SYMBOL_NEW(symbol), getter, setter);
                                                                                       ^
In file included from /root/.cache/node-gyp/10.24.1/include/node/node.h:63,
                 from ../swig_wrap.cxx:171:
/root/.cache/node-gyp/10.24.1/include/node/v8.h:3348:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
                                     ^~~~~~~~~~~
In file included from ../swig_wrap.cxx:171:
../swig_wrap.cxx: At global scope:
/root/.cache/node-gyp/10.24.1/include/node/node.h:573:43: warning: cast between incompatible function types from 'void (*)(v8::Handle<v8::Object>, v8::Handle<v8::Object>)' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/root/.cache/node-gyp/10.24.1/include/node/node.h:607:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../swig_wrap.cxx:3719:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(rgb, rgb_initialize)
 ^~~~~~~~~~~
In file included from /root/.cache/node-gyp/10.24.1/include/node/node.h:63,
                 from ../swig_wrap.cxx:171:
/root/.cache/node-gyp/10.24.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = SWIGV8_Proxy; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<SWIGV8_Proxy>&)]':
../swig_wrap.cxx:1126:112:   required from here
/root/.cache/node-gyp/10.24.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<SWIGV8_Proxy>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<SWIGV8_Proxy>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/10.24.1/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = SwigV8PackedData; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<SwigV8PackedData>&)]':
../swig_wrap.cxx:1404:95:   required from here
/root/.cache/node-gyp/10.24.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<SwigV8PackedData>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<SwigV8PackedData>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
  SOLINK_MODULE(target) Release/obj.target/rgblib.node
  COPY Release/rgblib.node
make: Leaving directory '/rgb-sdk/bindings/npm/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN rgblib@0.2.0-beta.1 No repository field.

added 97 packages from 66 contributors and audited 97 packages in 1414.575s
```

**Comment by youkchan** [comment]
I solved it myself.
Building it on docker(linux), Artifacts can't work on MacOS.
It's simple things.

But some trivial things on README better to be fixed I think.
(rust version. about running on MacOS...etc)
I will do a pull request.
